name: controller
description: Its designed to take data from any source and search
category: k8s
version: 1.2
maintainer: Rancher
license: Apache
projectURL: https://github.com/prachidamle/rancher-catalog-service/
